# Generated by Django 4.2.5 on 2023-11-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('开机', '开机'), ('关机', '关机'), ('调温', '调温'), ('调风', '调风'), ('结算', '结算')], default='0', max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('operator', models.CharField(default='0', max_length=20)),
                ('object', models.CharField(default='0', max_length=20)),
                ('room_number', models.CharField(default='0', max_length=20)),
                ('temperature', models.IntegerField(default=25)),
                ('speed', models.CharField(default='0', max_length=20)),
                ('cost', models.FloatField(default=0)),
                ('total_cost', models.FloatField(default=0)),
                ('status', models.CharField(default='0', max_length=20)),
                ('queue_status', models.CharField(default='0', max_length=20)),
                ('update_times', models.IntegerField(default=0)),
                ('temperature_upper', models.IntegerField(default=24)),
                ('temperature_lower', models.IntegerField(default=16)),
                ('low_speed_fee', models.FloatField(default=0.5)),
                ('mid_speed_fee', models.FloatField(default=1)),
                ('high_speed_fee', models.FloatField(default=2)),
                ('mode', models.CharField(default='0', max_length=20)),
            ],
        ),
    ]
