# Generated by Django 4.2.5 on 2023-11-09 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conditioners', '0006_conditioner_queue_status'),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='log',
            name='high_speed_fee',
        ),
        migrations.RemoveField(
            model_name='log',
            name='low_speed_fee',
        ),
        migrations.RemoveField(
            model_name='log',
            name='mid_speed_fee',
        ),
        migrations.RemoveField(
            model_name='log',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='log',
            name='queue_status',
        ),
        migrations.RemoveField(
            model_name='log',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='log',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='log',
            name='status',
        ),
        migrations.RemoveField(
            model_name='log',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='log',
            name='temperature_lower',
        ),
        migrations.RemoveField(
            model_name='log',
            name='temperature_upper',
        ),
        migrations.RemoveField(
            model_name='log',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='log',
            name='update_times',
        ),
        migrations.AddField(
            model_name='log',
            name='remark',
            field=models.CharField(default='无', max_length=100),
        ),
        migrations.AlterField(
            model_name='log',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conditioners.conditioner'),
        ),
        migrations.AlterField(
            model_name='log',
            name='operator',
            field=models.CharField(choices=[('客户', '客户'), ('管理员', '管理员'), ('系统', '系统')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(choices=[('入住', '入住'), ('结算', '结算'), ('开空调', '开空调'), ('关空调', '关空调'), ('调温', '调温'), ('调风', '调风'), ('请求服务', '请求服务'), ('结束服务', '结束服务'), ('调度', '调度'), ('产生费用', '产生费用')], default='0', max_length=20),
        ),
    ]
