# Generated by Django 4.2.5 on 2023-11-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_remove_log_cost_remove_log_high_speed_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='remark',
            field=models.CharField(default='无', max_length=1024),
        ),
    ]
