# Generated by Django 4.2.5 on 2023-11-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_alter_log_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(choices=[('入住', '入住'), ('结算', '结算'), ('开关机', '开关机'), ('调温', '调温'), ('调风', '调风'), ('请求服务', '请求服务'), ('结束服务', '结束服务'), ('调度', '调度'), ('产生费用', '产生费用')], default='0', max_length=20),
        ),
    ]
