# Generated by Django 4.2.5 on 2023-11-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_alter_log_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(default='0', max_length=20)),
                ('request_duaration', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('service_duaration', models.IntegerField(default=0)),
                ('speed', models.CharField(default='0', max_length=20)),
                ('cost', models.FloatField(default=0)),
                ('total_cost', models.FloatField(default=0)),
                ('fee', models.FloatField(default=0)),
            ],
        ),
    ]
