# Generated by Django 4.2.5 on 2023-10-14 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conditioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_now', models.IntegerField()),
                ('temperature_set', models.IntegerField()),
                ('mode', models.CharField(choices=[('0', '正常模式'), ('1', '节能模式'), ('2', '自动模式')], default='0', max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('room_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='acounts.user')),
            ],
        ),
    ]
