# Generated by Django 4.2.5 on 2023-10-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditioners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditioner',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='conditioner',
            name='update_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='conditioner',
            name='mode',
            field=models.CharField(choices=[('低风速', '低风速'), ('中风速', '中风速'), ('高风速', '高风速')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='conditioner',
            name='temperature_now',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='conditioner',
            name='temperature_set',
            field=models.IntegerField(default=25),
        ),
    ]
