# Generated by Django 4.2.5 on 2023-11-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditioners', '0002_conditioner_cost_conditioner_update_times_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditioner',
            name='mode_type',
            field=models.CharField(choices=[('制冷', '制冷'), ('制热', '制热'), ('检修', '检修')], default='0', max_length=20),
        ),
    ]
