# Generated by Django 4.2.5 on 2023-12-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditioners', '0007_alter_conditioner_temperature_now_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditioner',
            name='queue_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
