# Generated by Django 4.2.5 on 2023-12-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_group1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_group1",
            name="room_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
