# Generated by Django 4.2.5 on 2023-11-09 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0002_user_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cost',
        ),
    ]
