# Generated by Django 4.2.5 on 2023-12-07 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account_group1", "0001_initial"),
        ("acounts", "0003_remove_user_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_group1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account_group1.user_group1",
            ),
        ),
    ]
