@startuml
|顾客|
start
:提供身份证;
if (预约登记或现场申请) then (是)
  :身份核查;
  :缴纳押金;
  :登记入住;
  :提供门卡及空调密码;
else (否)
  :离开;
endif
:进入客房;;
:启动空调;
|中央空调管理员|
:设置计费规则和费率;
:启动中央空调;
|中控室|
:监控房间运行状态;
:分配空调资源;
|顾客|
:使用空调;
:调节风速和温度;
|中央空调管理员|
:处理报修信息;
|顾客|
:停止或中断服务;
|前台|
if (退房) then (是)
  :结算房费;
else (否)
  :生成空调使用详单;
endif
|酒店经理|
:生成空调运行日报和周报;
stop
@enduml
