@startuml
|前台营业员|
start
:等待顾客提出结账请求;
|顾客|
:提出结账请求;
|前台营业员|
:确认结账请求;
if (对账单是否有疑问) then (是)
  :查询详单;
  :生成空调使用详单;
  :提供详单;
else (否)
  :查询空调费用;
endif
:结账;
:打印账单和发票;
:更新空调状态;

|顾客|
:接收账单和发票;
|前台营业员|
:结束结账;
stop
@enduml
