@startuml

空调管理员 --> (配置计费规则)
空调管理员 --> (监控空调运行)
中控室 --> (监控空调运行)
中控室 --> (动态分配资源)

(配置计费规则) --> (设置计费率)

(监控空调运行) --> (跟踪客房状态)
(监控空调运行) --> (监控空气温度)
(监控空调运行) --> (监控设定温度)
(监控空调运行) --> (监控风速)
(监控空调运行) --> (监控当前费用)
(监控空调运行) --> (监控总费用)
(监控空调运行) --> (监控等待状态)

(动态分配资源) --> (确定优先级)
(动态分配资源) --> (分配空调设备)

@enduml