# Generated by Django 4.2.5 on 2023-11-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_upper', models.IntegerField(default=24, verbose_name='温度上限 (℃)')),
                ('temperature_lower', models.IntegerField(default=16, verbose_name='温度下限 (℃)')),
                ('mode', models.CharField(choices=[('制冷', '制冷'), ('制热', '制热'), ('检修', '检修')], default='0', max_length=20)),
                ('low_speed_fee', models.FloatField(default=0.5, verbose_name='低速风费率 (元/1C°)')),
                ('mid_speed_fee', models.FloatField(default=1, verbose_name='中速风费率 (元/1C°)')),
                ('high_speed_fee', models.FloatField(default=2, verbose_name='高速风费率 (元/1C°)')),
            ],
        ),
    ]
