# Generated by Django 4.2.5 on 2023-11-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
