# Generated by Django 4.2.5 on 2023-11-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_alter_settings_high_speed_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='mode',
            field=models.CharField(choices=[('制冷', '制冷'), ('制热', '制热'), ('检修', '检修')], default='1', max_length=20),
        ),
    ]
