@startuml

actor 顾客 as 顾客
actor 前台接待员 as "前台接待员"

顾客 --> (办理入住)
顾客 --> (办理退房)
前台接待员 --> (办理入住)
前台接待员 --> (办理退房)
酒店经理 --> (生成报告)

(办理入住) --> (分配客房)
(办理入住) --> (提供空调密码)
(办理入住) --> (查看空调面板)
(办理入住) --> (使用空调)

(办理退房) --> (结算客房费用)
(办理退房) --> (生成空调账单)
(办理退房) --> (提供详细空调使用信息)

(生成报告) --> (生成日报)
(生成报告) --> (生成周报)

@enduml